@startuml

图书管理员"1"--|>"many"图书书目
图书书目 *-- 借出图书
图书书目 o-- 预订图书
图书管理员"1"--|>"many"读者
读者 -- 查询借阅书籍情况
读者 --|> 取消预订
借出图书--书籍损坏
书籍损坏--|>图书采购员
借出图书--|>预订图书 : include
预订图书--取消预订 :generalization

class 图书采购员{
      采购缺少的图书
}
class 书籍损坏{
      购买新书籍
      处理损坏书籍
}
class 查询借阅书籍情况{
      查询借阅书籍数量
      查询归还书籍日期
      查询是否逾期归还
}
class 取消预订{
      取消不需要的书籍
      取消预订借书
}
class 读者{
      读者姓名
      读者身份证号码
      读者联系电话
      读者家庭住址
}
class 图书书目 {
      书籍种类
      书籍数量
      价格
      简介
}
class 借出图书{
      借出数量
      借出时间
}
class 预订图书{
      预订借书名称
      预订借书时间
}
@enduml